### ISSUE TITLE
Add a wizard/autodetection for default config

### ISSUE THREAD

**Issue by mmalecki** [nearform/nscale#16]
My Linux machine was configured by default (in `.nscale/config/config.json`) as using boot2docker, so I had to change some settings using wording like analyser which I never ever heard about before ;).

Could we possibly detect what OS user is on and apply the settings we think are the most  appropriate? (If we do that, we should tell users not to rely on this if they use the client in scripts in production and always ship their own config).

**Comment by mcollina** [comment]
This was fixed long ago :).
