### ISSUE TITLE
Output revision number from 'nsd container build'

### ISSUE THREAD

**Issue by dberesford** [nearform/nscale#30]
Small suggestion, would be nice if  'nsd container build' outputted the revision number that it just built, so you don't have to do a 'nsd revision list' to get the revision number before you do a deploy.

E.g. the current steps are:

    nsd container build sudc web
    nsd revision list sudc
    nsd revision deploy sudc <revision id>

If you could grab the revision id from the output of 'container build' then you wouldn't need the middle step:

    nsd container build sudc web
    nsd revision deploy sudc <revision id>

**Comment by darragh-hayes** [comment]
Building a container doesn't create a new system revision anymore, only a system compile does. Furthermore one can deploy like so "nscale rev dep latest." For these reasons I'm closing this for now.
