### ISSUE TITLE
Show the compiled platform on nsd revision list

### ISSUE THREAD

**Issue by rorywwalsh** [nearform/nscale#38]
It would be very helpful to know which platform a revision is compiled to. I'd suggest adding an extra column showing platform.

**Comment by darragh-hayes** [comment]
As was suggested about compiling for all platforms/targets and then deploying to a specific platform/target

a system is compiled for all targets now, e.g. on compile we could have `process.json,` `aws.json` and `development.json` and one deploys like so: ```nscale rev deploy xxxx latest aws```

there is a `deployed` column in the `revision list` which shows the target that a particular revision has been deployed to (if it has been deployed). With the above in mind, I'm going to close this issue for now.
