### ISSUE TITLE
Build not working without ForwardAgent

### ISSUE THREAD

**Issue by andreareginato** [nearform/nscale#47]
When running `nsd cont buildall` I can't clone the repository. 
To make it work you need to configure forwardAgent as follow.

```
# .ssh/config
host *
  ForwardAgent yes
```

**Comment by darragh-hayes** [comment]
Hi there, if you are working with nscale in aws/digitalocean etc, your machine will need some way to authenticate with github. You can either configure ForwardAgent to use your local machine's keys as you mentioned (which we now have documented) or you can generate a new keypair on the machine and associate it with your github account. Either will work. Closing this.

**Comment by mcollina** [comment]
The point here is getting this documented. Is it, @darragh-hayes? Can you please add a link to this issue to the explanation?
