### ISSUE TITLE
CLI 'nsd server status' command request

### ISSUE THREAD

**Issue by mcdonnelldean** [nearform/nscale#51]
Hi,

Just started playing with nscale, apologies if this is not the correct repo to ask this. I wanted to make a feature request for a cli command to check the status of the nscale server; if it is running or stopped.

`$ nsd server status`

I can see if this is something I can add myself if somebody points me in the right direction.

**Comment by McDonnellDean** [comment]
@mcollina on that subject, does nscale work on Windows? If so I would need to take this into account?

**Comment by mcollina** [comment]
nscale does not support windows at the moment.
Il giorno ven 2 gen 2015 alle 08:28 Dean McDonnell <notifications@github.com>
ha scritto:

**Comment by McDonnellDean** [comment]
@mcollina Cheers! That makes this change a wee bit easier so!

**Comment by darragh-hayes** [comment]
@McDonnellDean This was implemented see https://github.com/nearform/nscale-client/pull/49
