### ISSUE TITLE
Docs should include git ssh setup instuctions

### ISSUE THREAD

**Issue by jonyardley** [nearform/nscale#63]
After speaking with Matteo I found that I needed to set up a ssh key on my repository however this does not seem to be documented.

**Comment by McDonnellDean** [comment]
@jonyardley @mcollina Is this just a case of adding default how to setup SSH on a repo and a notice? If thats the case assign it to me and I'll get it added to the readme.

**Comment by jonyardley** [comment]
Aye, you got it. It might also be worth mentioning if you want to clone a repository over http(s), including your username and pass in the url - you need to still add the URL to your ssh config file otherwise it fails?

**Comment by mcollina** [comment]
@McDonnellDean please send a PR :). Thanks a million! I can't assign it to you, GH would not let me.

**Comment by McDonnellDean** [comment]
Will do @mcollina. @jonyardley Can you point me to where you were in the docs when you discovered you had an issue? Was it a particular repo or workshop? I'd like to add this info in the relevant place instead of just the main repo README.md

**Comment by McDonnellDean** [comment]
@jonyardley @mcollina Just bumping this again, see above, thanks!

**Comment by McDonnellDean** [comment]
@mcollina @jonyardley This is (will be) in the new docs see: https://github.com/McDonnellDean/nscale-docs/tree/core-additions 

This ticket can be closed

**Comment by mcollina** [comment]
Thanks!!
