### ISSUE TITLE
Error on very first nscale login (OSX)

### ISSUE THREAD

**Issue by McDonnellDean** [nearform/nscale#68]
Following the workshop (nscale@0.14.pre.7):

- docker / boot2docker installed
- git credentials set up
- boot2docker running, docker command working
- nscale installed globally, server start / server stop works

Crash occurs when `nscale login` is ran:

``` bash
mpb:~ mcdonnelldean$ nscale server start
nscale servers starting..
done!
mpb:~ mcdonnelldean$ nscale login

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: connect ECONNREFUSED
    at errnoException (net.js:905:11)
    at Object.afterConnect [as oncomplete] (net.js:896:19)
```
 
Logs from `nscale server logs`

``` bash
{"name":"nfd-kernel","hostname":"mpb.local","pid":464,"level":30,"msg":"booting","time":"2015-02-23T22:46:32.949Z","v":0}
Uncaught Error: Cannot find module '../build/Debug/nodegit'

FROM
Function.Module._resolveFilename (module.js:340:11)
Function.Module._load (module.js:280:25)
Module.require (module.js:364:17)
require (module.js:380:17)
Object.<anonymous> (/usr/local/lib/node_modules/nscale/node_modules/nscale-kernel/node_modules/nodegit/lib/nodegit.js:12:12)
Module._compile (module.js:456:26)
Object.Module._extensions..js (module.js:474:10)
Module.load (module.js:356:32)
Function.Module._load (module.js:312:12)
Module.require (module.js:364:17)
require (module.js:380:17)
Object.<anonymous> (/usr/local/lib/node_modules/nscale/node_modules/nscale-kernel/lib/sysrev/gitutil.js:18:12)
Module._compile (module.js:456:26)
Object.Module._extensions..js (module.js:474:10)
Module.load (module.js:356:32)
Function.Module._load (module.js:312:12)
Module.require (module.js:364:17)
require (module.js:380:17)
Object.<anonymous> (/usr/local/lib/node_modules/nscale/node_modules/nscale-kernel/lib/sysrev/sysrev.js:23:11)
Module._compile (module.js:456:26)
Object.Module._extensions..js (module.js:474:10)
Module.load (module.js:356:32)
Function.Module._load (module.js:312:12)
Module.require (module.js:364:17)
require (module.js:380:17)
new module.exports (/usr/local/lib/node_modules/nscale/node_modules/nscale-kernel/lib/kernel.js:58:13)
Object.<anonymous> (/usr/local/lib/node_modules/nscale/node_modules/nscale-kernel/bin/_nscale-kernel.js:31:14)
Module._compile (module.js:456:26)
Object.Module._extensions..js (module.js:474:10)
Module.load (module.js:356:32)
Function.Module._load (module.js:312:12)
Function.Module.runMain (module.js:497:10)
startup (node.js:119:16)
node.js:929:3

```

Installed Modules:

```
├── azure-cli@0.8.13
├── grunt-cli@0.1.13
├── mocha@2.1.0
├── n@1.2.9
├── nodegit@0.2.7
├── npm@1.4.28
└── nscale@0.14.0-pre.7
```

**Comment by mcollina** [comment]
How did you install node? Which version of node?

That happens if nodegit installation failed somehow, try reinstalling.

**Comment by McDonnellDean** [comment]
Node: V0.12.0

@mcollina For nodegit, should it have installed itself as a dependency? I will reinstall it tonight to see if it throws or err's. I ask because we should probably make end users aware of the need to have it in the docs.

**Comment by darragh-hayes** [comment]
@McDonnellDean nodegit should be installed as part of the nscale installation. I experienced a very similar issue re: nodegit not being installed on a linux machine. Unfortunately I never documented how I got it to work. But I think I had to completely reinstall a stable release of node.

**Comment by McDonnellDean** [comment]
@darragh-hayes Thanks, I tried to install clean again, node, the lot. We need to document this too though.

**Comment by mcollina** [comment]
How did you install node? Which version of OS X are you using?

Also consider that 0.12 support is at max experimental. If any of you can confirm that it all works it would be great (it should, but it needs a check). I am a fan of NVM to switch between node versions.

**Comment by McDonnellDean** [comment]
- I use `n` to manage installs
- OSX Yosemitie

I can drop down to Stable to check again when I am at the machine. I'll update when I retry.

**Comment by darragh-hayes** [comment]
closing this issue as it's more of an issue with the setup you had on your machine. We've also gone past 0.14.pre.7

**Comment by McDonnellDean** [comment]
Cheers Darragh, i know how to repro too, I'll send on details when I have time
