### ISSUE TITLE
New aws instance started by "system fix" is not linked to elb

### ISSUE THREAD

**Issue by darragh-hayes** [nearform/nscale#72]
I was doing some tesing with the following versions in aws:

nscale 		 0.14.2
nscale-kernel 	 0.14.14
nscale-client 	 0.14.7
nscale-web 	 0.10.0
nscale-api 	 0.10.0

I successfully deployed the SUDC and killed the instance running the web container. I ran a system check/system fix which started up a new instance running the web container but the instance was not linked to the elb. So the web front end was not accessible through the elb domain name

**Comment by mcollina** [comment]
Confirmed. A fix will come for 0.15.

**Comment by mcollina** [comment]
Should be fixed in 0.15.0-pre2. Install it with `npm install nscale@next -g`.
