### ISSUE TITLE
container name clash possible

### ISSUE THREAD

**Issue by rjrodger** [nearform/nscale#83]
if you have two separate container definition files in the `definitions` folder, and they both have a container with the same name, then... bad stuff

**Comment by mcollina** [comment]
how do you propose to fix this? Giving an error to the user?
Il giorno mer 6 mag 2015 alle 19:05 Richard Rodger <notifications@github.com>
ha scritto:

**Comment by Nss** [comment]
+1 for showing an error to the user with the name of the duplicate definitions and the files containing them.

**Comment by mcollina** [comment]
This is fixed in 0.16.
