### ISSUE TITLE
Building containers failing

### ISSUE THREAD

**Issue by djumanoff** [nearform/nscale#99]
When I try to build container with command: nscale container build nscaledemo web latest development .  It fails with the following message 

Get https://index.docker.io/v1/repositories/library/node/images: dial tcp: lookup index.docker.io on 192.168.0.1:53: read udp 192.168.0.1:53: i/o timeout

{ cmd: 'git checkout -q 92ea17ace03f9184ca0818707b952f7ad64f8d1d && echo checked out 92ea17ace03f9184ca0818707b952f7ad64f8d1d && docker build -t localhost:8011/touchka/web-92ea17ace03f9184ca0818707b952f7ad64f8d1d . && RESULT=$? && git reset -q HEAD . && (exit $RESULT)',
  code: 1 }
{ cmd: 'git checkout -q 92ea17ace03f9184ca0818707b952f7ad64f8d1d && echo checked out 92ea17ace03f9184ca0818707b952f7ad64f8d1d && docker build -t localhost:8011/touchka/web-92ea17ace03f9184ca0818707b952f7ad64f8d1d . && RESULT=$? && git reset -q HEAD . && (exit $RESULT)',
  code: 1 }
command failed

**Comment by djumanoff** [comment]
Mac OS X 10.10.4

**Comment by AdrianRossouw** [comment]
It almost looks like it is having issues connecting to boot2docker?

what does `boot2docker status` give you?

**Comment by djumanoff** [comment]
<code>boot2docker status</code> command gives me: 
running

**Comment by djumanoff** [comment]
Issue was resolved. I think it was something wrong with connectivity to docker hub or something... Anyways it disappears.
